source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!
target 'pokeberries' do
  pod 'Material', '1.41.2'
  pod 'PokemonKit'
  pod 'AlamofireImage', '~> 2.0'
  pod 'Persei', '~> 2.0.1'
  pod 'RealmSwift', '0.103.1'
  pod 'Charts/Realm'
  pod 'ARSLineProgress', '~> 1.0'
  target 'pokeberriesTests' do
    inherit! :search_paths

  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts target.name
  end
end
